name: formini
description: Simple yet powerful form state management
version: 0.0.1-alpha.1
author: Jari Pekkala <jari@vantage.fi>
homepage: https://github.com/vantageoy/formini

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  redux: ^3.0.0
  flutter_redux: ^0.5.3
  schemani: 
    path: '../schemani'
  
dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
