name: formini
description: Simple yet powerful form state management
version: 0.0.1-alpha.1
author: Jari Pekkala <jari@vantage.fi>
homepage: https://github.com/vantageoy/formini

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  bloc: ^0.15.0
  flutter_bloc: ^0.21.0
  rxdart: ^0.22.2
  
dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
